### ISSUE TITLE
ValueError: ECB mode does not use IV

### ISSUE THREAD

**Issue by acseckin** [xribene/Emokit_Epoc_GUI#2]
When I try your code editor gives me this error massage

```
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\ACSECKIN\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\ACSECKIN\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\ACSECKIN\Anaconda2\lib\site-packages\emokit\decrypter.py", line 49, in run
    cipher = self.new_cipher(self.verbose)
  File "C:\Users\ACSECKIN\Anaconda2\lib\site-packages\emokit\decrypter.py", line 120, in new_cipher
    return AES.new(crypto_key(self.serial_number, self.is_research, verbose), AES.MODE_ECB, iv)
  File "C:\Users\ACSECKIN\Anaconda2\lib\site-packages\Crypto\Cipher\AES.py", line 94, in new
    return AESCipher(key, *args, **kwargs)
  File "C:\Users\ACSECKIN\Anaconda2\lib\site-packages\Crypto\Cipher\AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "C:\Users\ACSECKIN\Anaconda2\lib\site-packages\Crypto\Cipher\blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: ECB mode does not use IV
```

**Comment by jamesdu0504** [comment]
I also encountered this problem, which has not been solved yet. Have you solved the problem?
Thank you very much!

**Comment by xribene** [comment]
Hey both. Unfortunatelly I don't have access to an Epoc headset anymore, so I can't help you debug it. The error you mention, is related to the emokit library and more precise the pycrypto package. The GUI I made, is a layer above the emokit library, and assumes that first you can successfuly couple the Epoc with the emokit. Try first their examples from their repository and make sure it works. Notice that if your Epoc is a newer model (after 2016), it won't work with emokit.

**Comment by jamesdu0504** [comment]
OK, I see. I'll try using an earlier version of Crypto. I don't know if python2.7 or python3.4 will solve this problem.
